add_newline = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[aws]
disabled = true

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = 75
symbol = "☰ "

[directory]
disabled = false
truncate_to_repo = true